#!/usr/bin/python

import json
from random import randint
import sys


try:
    content = json.loads(open(sys.argv[1],'r').read())
except Exception as e:
    print("Failed to load self-test. Did you provide the right file name as the first argument?")
    raise e

total = 0
correct = 0

while len(content) > 0:
    q = content.pop(randint(0,len(content)-1))
    total += 1
    print(q['Q'])
    a=input("# ")
    if a == q['A']:
        correct += 1

print("Total: {}\tCorrect: {}\tGrade: {}%".format(
    total,
    correct,
    int((correct/total)*100)))
